# Generated by Django 2.0.2 on 2018-02-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20180221_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='album',
            name='melon_id',
        ),
    ]
