# Generated by Django 2.0.2 on 2018-02-08 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='곡 제목')),
                ('genre', models.CharField(max_length=100, verbose_name='장르')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='가사')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Album')),
            ],
        ),
    ]
