# Generated by Django 2.0.2 on 2018-02-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20180208_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='melon_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='멜론 SONG ID'),
        ),
    ]
