# Generated by Django 2.0.2 on 2018-02-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_song_melon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='melon_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='멜론 SONG ID'),
        ),
    ]
