# Generated by Django 2.0.2 on 2018-02-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_song_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(blank=True, to='artist.Artist', verbose_name='아티스트 목록'),
        ),
        migrations.AlterField(
            model_name='song',
            name='melon_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='멜론 Song ID'),
        ),
    ]
